### ISSUE TITLE
mysql 的 upsert 中值 Z 会变成 undefined

### ISSUE THREAD

**Issue by XxLittleCxX** [shigma/minato#17]
```ts
await ctx.database.upsert('foo', [{ bar: 'Z' }])
```

https://github.com/shigma/minato/blob/eea9eb710a783fa9a030a2fefb775eb39296f29a/packages/sql-utils/src/index.ts#L331

**Comment by shigma** [comment]
用的哪个数据库

**Comment by shigma** [comment]
请给出更多上下文。我无法复现此问题。推测是你误用了 upsert。

**Comment by XxLittleCxX** [comment]
```ts
  ctx.model.extend('test', {
    primary: 'string',
    column: 'timestamp'
  }, {
    primary: 'primary'
  })

  await ctx.database.upsert('test', [{primary: 'abc', column: 'Z'}])

[
  'INSERT INTO `test` (`primary`, `column`)',
  "VALUES ('abc', 'undefined')",
  'ON DUPLICATE KEY UPDATE `column` = VALUES(`column`)'
]
```

**Comment by Nikaidou-Shinku** [comment]
我猜测 `undefined` 是[这里](https://github.com/shigma/minato/blob/eea9eb710a783fa9a030a2fefb775eb39296f29a/packages/sql-utils/src/index.ts#L338)产生的。
根本原因应该是 `MySQLBuilder` 的 `escapeMap` 有误，[此处](https://github.com/shigma/minato/blob/eea9eb710a783fa9a030a2fefb775eb39296f29a/packages/mysql/src/index.ts#L97)误用了 `\Z`。

我不太熟悉数据库，所以不清楚这里的转义表每一项分别起什么作用，但是 JavaScript 的正则表达式看上去会把 `\Z`（包括 `\z`）仅仅看作字符 Z 而不是让它匹配文本末尾（无论是否使用多行模式）。
无论如何，它都无法匹配出 `\x1a` 这个字符，因此 `this.escapeMap[match[0]]` 得到了 `undefined`。

**Comment by shigma** [comment]
你是对的。这里或许应该用 `\x1a` 代替 `\z`。
