### ISSUE TITLE
Bug: MySQL下重复添加联合索引导致索引数超出MySQL范围

### ISSUE THREAD

**Issue by ifrvn** [shigma/minato#25]
## 问题描述

本地调试插件时突然出现报错
`ER_TOO_MANY_KEYS: Too many keys specified; max 64 keys allowed`

![image](https://user-images.githubusercontent.com/21982381/234903577-d4ed8f6e-74c5-41c8-be4b-1d26934bc867.png)

## 复现过程

插件中建一个表，并设置联合索引

```typescript
ctx.model.extend('test', {
  id: 'unsigned',
  test1: 'string',
  test2: 'string',
}, {
  autoInc: true,
  unique: [['test1', 'test2']],  // 这里使用联合索引
})
```

然后每次reload插件，查看MySQL的`INFORMATION_SCHEMA.KEY_COLUMN_USAGE`表，都能观察到新建了索引

![image](https://user-images.githubusercontent.com/21982381/234904936-949866cd-cd58-40ba-a9bb-19af09b7d974.png)

64次后就会出现以上报错

## 版本

MySQL 8
koishi 4.12.6
@koishijs/plugin-database-mysql 5.4.4

**Comment by ilharp** [comment]
![image](https://user-images.githubusercontent.com/20179549/234938166-563aa000-a2ae-406f-9d04-28c2005a622b.png)

刚刚看了下，竟然真的存在这个问题，感觉还挺严重的，希望官方能够尽快修复

**Comment by shigma** [comment]
问题应该已经修复，麻烦使用最新版本测试一下。如果仍然不行我会重新开启此 issue。
