### ISSUE TITLE
Bug: 当value为null/undefined时upsert/get的行为不一致

### ISSUE THREAD

**Issue by Hieuzest** [shigma/minato#28]
以如下定义为例
```
interface TestFields {
  id: number
  a: string
  b: string
  c: string
}

ctx.model.extend('foo/test', {
  id: 'unsigned',
  a: 'string',
  b: 'string',
  c: 'string',
}, {autoInc: true})
```
执行如下代码：
```
await ctx.database.upsert('foo/test', [{ a: 'foo', c: 'foobar' }], ['a', 'b'])
```
- sqlite: 添加一条b:""的记录
- mongo: 当有b:null时执行更新，否则添加一条b:""的记录
```
await ctx.database.upsert('foo/test', [{ a: 'foo', b: null, c: 'foobar' }], ['a', 'b'])
```
- sqlite: 正常（有b:null时执行更新，否则添加一条b:null的记录）
- mongo: 添加一条b:null的记录

```
await ctx.database.upsert('foo/test', [{ a: 'foo', b: undefined, c: 'foobar' }], ['a', 'b'])
```
- sqlite: 添加一条b:null的记录
- mongo: 添加一条b:null的记录

除此之外，mongo当`get('foo/test', {a:'foo', b:null / undefined})`时有
https://github.com/shigma/minato/blob/c32e15c2e47c08dc4b2be715ee00a9795951cb68/packages/mongo/src/utils.ts#L25-L27
从而在测试中返回空，不清楚是由于设计还是什么原因，不过sqlite执行同样代码，会返回所有b:null的记录，
mongodb原生的query的行为也是返回所有b:null的记录

**Comment by shigma** [comment]
这个是不是解决了

**Comment by Hieuzest** [comment]
是我最早的时候对upsert理解有误，上述upsert均为错误用法
