### ISSUE TITLE
Bug: Expression related issues

### ISSUE THREAD

**Issue by Hieuzest** [shigma/minato#32]
此处汇总一些测试中发现的其他 bug

- sqlite在set/upsert时只select了update中既有的fields，没有考虑经由expression引入的其他fields，从而导致getRecursive失败

https://github.com/shigma/minato/blob/c32e15c2e47c08dc4b2be715ee00a9795951cb68/packages/sqlite/src/index.ts#L341
https://github.com/shigma/minato/blob/c32e15c2e47c08dc4b2be715ee00a9795951cb68/packages/sqlite/src/index.ts#L376-L378
我建议是都sqlite了，直接读整行如何？

- mysql 使用dot notation声明的field在expreval中错误地作为json处理，比如

https://github.com/shigma/minato/blob/c32e15c2e47c08dc4b2be715ee00a9795951cb68/packages/tests/src/object.ts#L4-L13
https://github.com/shigma/minato/blob/c32e15c2e47c08dc4b2be715ee00a9795951cb68/packages/tests/src/object.ts#L20-L24
此时如果有getRecursive涉及到 `meta.a` `meta.embed`， 会被处理为`meta` 的json field， 从而找不到field

**Comment by shigma** [comment]
> 我建议是都sqlite了，直接读整行如何？

支持。欢迎 PR 修复问题并完善测试。

> mysql 使用dot notation声明的field在expreval中错误地作为json处理

你说的对。同样欢迎 PR。或者我之后来修。
