### ISSUE TITLE
Feature: Introduce ObjectId as primary key for mongo

### ISSUE THREAD

**Issue by Hieuzest** [shigma/minato#35]
## Motivation
Auto-increment primary keys are introduced in cases where no fields can be used as primary naturally.
However, there are non-negligible overhead when using autoInc in mongo driver.
Therefore we propose to use the native ObjectId as auto-generated primary key for mongo and provide universal interface to support it while still maintaining consistency with other drivers.

## Design
Introduce new tagged type `Primary` (name is not decided yet) and new field type `primary`
The `Primary` type contains auto-generated value, and can only use as primary keys or foreign keys. Also it is unordered.
When `Primary` occurs as primary key, `autoInc` and `optimizeIndex` must be set.

In mongo driver, `Primary` is treated as ObjectId (therefore omitted in many situations), while in SQL-based drivers, `Primary` is treated as proper auto-increment intergers.

先占坑，看看有什么别的思路x

**Comment by Hieuzest** [comment]
f19854410ead2702726aa20ae2a24d5cf89c4913
waiting for other PRs

**Comment by shigma** [comment]
> [f198544](https://github.com/shigma/minato/commit/f19854410ead2702726aa20ae2a24d5cf89c4913)

我感觉可以直接默认 (忽略) autoInc 属性。即有 primary 的时候，无论是否 autoInc，在 SQL 上均视为 autoInc，在 mongo 均视为 ObjectId。
