### ISSUE TITLE
所有测试全都是Memory Database

### ISSUE THREAD

**Issue by simon300000** [shigma/minato#5]
是有什么原因吗

https://github.com/shigma/minato/blob/f16d19e78e4d848ca6d62eff46424e5359fc60be/packages/mongo/tests/index.spec.ts#L4
https://github.com/shigma/minato/blob/f16d19e78e4d848ca6d62eff46424e5359fc60be/packages/mysql/tests/index.spec.ts#L4
https://github.com/shigma/minato/blob/f16d19e78e4d848ca6d62eff46424e5359fc60be/packages/level/tests/index.spec.ts#L5
https://github.com/shigma/minato/blob/f16d19e78e4d848ca6d62eff46424e5359fc60be/packages/sqlite/tests/index.spec.ts#L5

**Comment by shigma** [comment]
忘记改了 🤣

**Comment by simon300000** [comment]
咦 考虑把level升级一下吗 新版本@8自带subleveldown

**Comment by shigma** [comment]
可以，欢迎 PR（

**Comment by simon300000** [comment]
我有个draft 但是你可能猜到了 我不会写type
